server:
  port: 8080
  servlet:
    context-path: ''

spring:
  application:
    name: 'Spring Boot Sandbox'
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    org.springframework.web: INFO
    com.foolishpuma: TRACE
